Homework_1: Git
daraffleur/green_lantern pull request #1
Opened 2020-03-09 17:37 UTC by daraffleur

2020-03-09 18:42 UTC, olikhosherstov commented on lantern/git/homework.py
> +
Функція повинна повернути  dictionary, а не list.  {key: value}   key - 'a' -> 'z'; value - 1 -> 27

2020-03-09 18:45 UTC, olikhosherstov commented on lantern/git/homework.py
> +
не можна змінювати вхідний аргумент функції потрібно працювати з його копією.
`data_copy = data [ : ] `

2020-03-09 18:48 UTC, olikhosherstov commented on lantern/git/homework.py
> +
потрібно спробувати конвертувати аргументи у int, тут перевірка на тип не потрібнаю int(first_value)

2020-03-09 18:52 UTC, olikhosherstov commented on lantern/git/homework.py
> +
за умовою завдання потрібно перевірити аргументи. Якщо вони integer то виконати множення.

2020-03-09 22:22 UTC, DimmeGz commented on lantern/git/homework.py
> +            raise TypeError
if isinstance(i, int) при змінній на вході типу bool поверне True і далі працюватиме зі змінною як з 0 або 1. Потрібно додати перевірку на булеві значення.

2020-03-09 22:22 UTC, DimmeGz commented on lantern/git/homework.py
> +        second = int(second_value)
можна скоротити код, записавши це в один рядок: first, second = int(first_value), int(second_value)

2020-03-09 22:22 UTC, DimmeGz commented on lantern/git/homework.py
>      return positive_number
не обов'язково вводити нову змінну. Можна просто написати return positive_number = [number for number in data if number > 0]

2020-03-12 13:15 UTC, dimigor requested changes

2020-03-12 13:15 UTC, dimigor commented on lantern/git/homework.py
> +        raise TypeError
difficult logic. Can you simplify it?

2020-03-12 13:15 UTC, dimigor commented on lantern/git/homework.py
> +        first, second = int(first_value), int(second_value)
this line is not necessary, you can just return multiplying with converting

2020-03-12 13:15 UTC, dimigor commented on lantern/git/homework.py
> +    except (TypeError or ValueError):
You should separate errors by comma

2020-03-12 13:15 UTC, dimigor commented on lantern/git/homework.py
> +
too many blank lines between functions. There have to be 2 blank lines

2020-03-12 13:15 UTC, dimigor commented on lantern/git/homework.py
> +    return dict(zip(range(1, 27), string.ascii_lowercase))
Suppose in the English alphabet was added one new letter. Then you will need to change your code. Do this function better. Please do not hardcode some values, like in `range`

2020-03-13 16:28 UTC, dimigor approved these changes

2020-03-13 16:28 UTC, dimigor commented on lantern/git/homework.py
> +    return dict(enumerate(ascii_lowercase, 1))
very nice

2020-03-13 16:28 UTC, dimigor commented on lantern/git/homework.py
> +    return sorted_list
do not forget about the last line. It needs to be blank

2020-04-21 10:41 UTC, merged