Django orm intro
daraffleur/green_lantern pull request #11
Opened 2020-06-02 15:12 UTC by daraffleur

2020-06-10 17:38 UTC, dimigor requested changes

2020-06-10 17:38 UTC, dimigor commented on lantern/django/django_intro/src/apps/articles/models.py
> +        return 'Welcome to the %s' % self.name
please do not use `%formating`. 
Always use for python3 - `f-strings`, for python2 - `.format()`

2020-06-10 17:38 UTC, dimigor commented on lantern/django/django_intro/src/apps/articles/models.py
> +    id_of_menu = models.ForeignKey(Menu, db_column='id_of_menu', blank=True, null=False, on_delete=models.DO_NOTHING, db_constraint=False)
instead of `id_of` naming it `menu_id`

2020-06-10 17:38 UTC, dimigor commented on lantern/django/django_intro/src/apps/articles/models.py
> +#     )
please, do not commit commented code
you would never again use commented code

2020-06-13 10:29 UTC, daraffleur commented on lantern/django/django_intro/src/apps/articles/models.py
> +        return 'Welcome to the %s' % self.name
Done!

2020-06-13 10:29 UTC, daraffleur commented on lantern/django/django_intro/src/apps/articles/models.py
> +    id_of_menu = models.ForeignKey(Menu, db_column='id_of_menu', blank=True, null=False, on_delete=models.DO_NOTHING, db_constraint=False)
Done!

2020-06-13 10:29 UTC, daraffleur commented on lantern/django/django_intro/src/apps/articles/models.py
> +#     )
Done!

2020-06-15 17:49 UTC, dimigor approved these changes

2020-06-17 14:56 UTC, merged